# Generated by Django 3.2.7 on 2021-09-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='oy',
            field=models.CharField(default='N/a', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='single_photo',
            field=models.FileField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='article',
            name='yil',
            field=models.SmallIntegerField(default=None),
        ),
    ]
